# Generated by Django 3.1.7 on 2021-03-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210318_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='SD',
            field=models.BooleanField(default=True, verbose_name='Наличие SD карты'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_volume_max',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Максимальный объем встраиваемой памяти'),
        ),
    ]
