# Generated by Django 3.1.7 on 2021-03-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210318_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='SD',
            new_name='sd',
        ),
    ]
